# Generated by Django 3.0.3 on 2023-08-31 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('established_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friend_requests_sent', to='social.AppUser')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friend_requests_received', to='social.AppUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='gene',
            name='ec',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='sequencing',
        ),
        migrations.RemoveField(
            model_name='geneattributelink',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='geneattributelink',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gene',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='EC',
        ),
        migrations.DeleteModel(
            name='Gene',
        ),
        migrations.DeleteModel(
            name='GeneAttributeLink',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sequencing',
        ),
    ]
