# Generated by Django 3.0.3 on 2023-09-01 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20230901_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='user_id',
        ),
    ]
