# Generated by Django 3.0.3 on 2023-09-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20230901_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user_id',
            new_name='user',
        ),
    ]
