# Generated by Django 3.0.3 on 2023-09-02 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_statusupdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusUpdate',
            new_name='Status',
        ),
        migrations.AlterField(
            model_name='status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.AppUser'),
        ),
    ]
